### ISSUE TITLE
Bug with tsconfig since @2.4.1

### ISSUE THREAD

**Issue by kravetsone** [privatenumber/pkgroll#77]
### Problem

```bash
error TS5095: Option 'bundler' can only be used when 'module' is set to 'preserve' or to 'es2015' or later.
error TS5109: Option 'moduleResolution' must be set to 'NodeNext' (or left unspecified) when option 'module' is set to 'NodeNext'.

Error [RollupError]: [plugin dts] src/index.ts: Failed to compile. Check the logs above.
    at getRollupError (Z:\PROJECTS\node-ts\GRAMIO\prompt\node_modules\rollup\dist\shared\parseAst.js:282:41)
    at Object.error (Z:\PROJECTS\node-ts\GRAMIO\prompt\node_modules\rollup\dist\shared\parseAst.js:278:42)
    at Object.error (Z:\PROJECTS\node-ts\GRAMIO\prompt\node_modules\rollup\dist\shared\rollup.js:804:32)
    at Object.error (Z:\PROJECTS\node-ts\GRAMIO\prompt\node_modules\rollup\dist\shared\rollup.js:19882:42)
    at generateDtsFromTs (Z:\PROJECTS\node-ts\GRAMIO\prompt\node_modules\pkgroll\dist\rollup-plugin-dts-Bhb-wA8a.js:30:1753)
    at Object.transform (Z:\PROJECTS\node-ts\GRAMIO\prompt\node_modules\pkgroll\dist\rollup-plugin-dts-Bhb-wA8a.js:30:1861)
    at Z:\PROJECTS\node-ts\GRAMIO\prompt\node_modules\rollup\dist\shared\rollup.js:989:40 {
  id: 'Z:\\PROJECTS\\node-ts\\GRAMIO\\prompt\\src\\index.ts',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'dts',
  watchFiles: [ 'Z:\\PROJECTS\\node-ts\\GRAMIO\\prompt\\src\\index.ts' ],
  [Symbol(augmented)]: true
}
```

```json
{
	"compilerOptions": {
		"lib": ["ESNext"],
		"target": "ES2022",
		"module": "NodeNext",
		"moduleDetection": "force",

		/* Bundler mode */
		"moduleResolution": "NodeNext",
		/* Linting */
		"skipLibCheck": true,
		"strict": true,
		"noFallthroughCasesInSwitch": true,
		"forceConsistentCasingInFileNames": true,
		"composite": true,
		"baseUrl": "./src",
		"rootDir": "./src",
		"outDir": "./dist"
	},
	"include": ["./src"],
	"exclude": ["./dist"]
}
```

### Expected behavior

all works fine on 2.4.0

### Minimal reproduction URL

https://github.com/gramiojs/prompt

### Version

v2.4.1

### Node.js version

v20.12.2

### Package manager

bun

### Operating system

Windows

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by bisubus** [comment]
Same issue here with 2.4.1. Also `pkgroll --tsconfig=tsconfig.pkgroll.json` doesn't recognize custom config that fulfills the requirements:

```
{
  "compilerOptions": {
    "module": "es2022",
    "moduleResolution": "bundler"
  },
  "extends": "./tsconfig.json",
}
```

**Comment by privatenumber** [comment]
Looks like this is caused by https://github.com/privatenumber/pkgroll/commit/ef6265c1dd9021adff718fc09bd86068bb161eb9#diff-307257d0e9b96b361115dbf7924a0aa9509d426afff26053a5a36912402c39b6R80

@bisubus Can you copy-paste the error you're getting?

**Comment by bisubus** [comment]
@privatenumber The reproduction for custom tsconfig https://github.com/bisubus/node-app-template/tree/pkgroll-tsconfig

The error is exactly the same as in the issue,

```
error TS5095: Option 'bundler' can only be used when 'module' is set to 'preserve' or to 'es2015' or later.
error TS5109: Option 'moduleResolution' must be set to 'NodeNext' (or left unspecified) when option 'module' is set to 'NodeNext'.

Error [RollupError]: [plugin dts] src/index.ts: Failed to compile. Check the logs above.
    at getRollupError (...\node_modules\rollup\dist\shared\parseAst.js:282:41)
    at Object.error (...\node_modules\rollup\dist\shared\parseAst.js:278:42)
    at Object.error (...\node_modules\rollup\dist\shared\rollup.js:804:32)
    at Object.error (...\node_modules\rollup\dist\shared\rollup.js:19882:42)
    at generateDtsFromTs (...\node_modules\pkgroll\dist\rollup-plugin-dts-Bhb-wA8a.js:30:1753)
    at Object.transform (...\node_modules\pkgroll\dist\rollup-plugin-dts-Bhb-wA8a.js:30:1861)
    at ...\node_modules\rollup\dist\shared\rollup.js:989:40 {
  id: '...\\src\\index.ts',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'dts',
  watchFiles: [ 'C:\\Dev\\fastify-template\\src\\index.ts' ],
  [Symbol(augmented)]: true
}
```
